### ISSUE TITLE
superfluous factor in sleepTime equation

### ISSUE THREAD

**Issue by genie-eng** [kata198/python-nonblock#1] opened 2016-12-14 22:20 UTC
For your equation in bgwrite: 
    sleepTime = charityTime * ((dataWritten / delta) / ( (dataWritten / delta) * priorityPctDec))
It seems that the factor (dataWritten / delta) will be cancelled anyway, so it does not matter for sleepTime. Do you mean some other way that dataWritten or delta might matter?

Thanks!
Jeff

**Comment by kata198** [comment] 2016-12-15 02:33
Generally I try to write everything out and not simplify so it's clear what
is being considered in the equation. I assume the compiler will optimize
it, and if not basic math has almost no impact and readability is important.

HOWEVER - You are correct here, the equation as written is basically
charityTime / priorityPctDec .

I have made a mistake here.

Basically, what I was trying to do is the following:


"priorityPctDec" should be a ratio of > 0.0 to 1.0, and represents the
total amount of bandwidth we use. So at a priorityPct of 50, we want to use
50% total bandwidth. Since write operations are unthrottled, the idea is
that we want to use 50% of total bandwidth by writing at maximum and then
sleeping for the remainder of the period, so that we average out at 50%
bandwidth.

So dataWritten / delta = our current bandwidth. aka "bandwidth rate"

priorityPctDec = percentage of total bandwidth we should try to utilize

charityTime = the period of inactivity that we will allow in order to
achieve an overall rate of priorityPct % total bandwidth.


The issue is that the current equation doesn't take into account "rate", it
is just a proportion of charityTime and priorityPct, which is not my intent.

Given this, even though the equation is incorrect, the BG_IO_PRIOS were
calculated by measuring write performance vs expected performance, so it
DOES work somewhat as intended, even though the algorithm does not work as
intended.

Do you have an algorithm in mind which achieves the above goals? If we
change the algorithm, we will also need to change the precalcualted values
for BG_IO_PRIOS.

I am open to your suggestions.

Thanks,
Tim

**Comment by kata198** [comment] 2016-12-15 02:38
Also, as an addendum to my previous comment, you should notice that in all
the BG_IO_PRIOS, the charityRate and charityTime never change. So really
what we are doing is that the higher priority (lower number) uses larger
chunk sizes, and sleeps the least (a constant charityTime divided by an
ever-decreasing priorityPct).

So again, it DOES work and DOES achieve the intended result, but I don't
disagree that we could use a better algorithm that actually takes the
current rate into consideration in the sleep time.

Feel free to suggest something better that is also supported with numbers,
and I will strongly consider implementing it.

**Comment by kata198** [comment] 2016-12-15 04:37
Okay, after I ate and relaxed a bit, it seems very obvious how to achieve
my intent:

@@ -252,20 +258,25 @@ class BackgroundWriteProcess(threading.Thread):
             doFlush(fileObj)

             dataWritten += len(nextData)
-
-            if i == charityPeriod:
+
+            if True:
+#            if i == charityPeriod:
                 # We've completed a full period, time for charity
                 after = time.time()

                 delta = after - before
                 # Uncomment the following to see rates

-#                sys.stdout.write('\t  I have written %d bytes in %3.3f
seconds (%4.5f M/s)\n' %(dataWritten, delta, (dataWritten / delta) /
(1024*1024)  ))
-#                sys.stdout.flush()
+                rate = dataWritten / delta
+
+                if DEBUG is True:
+                    sys.stdout.write('\t  I have written %d bytes in %3.3f
seconds (%4.5f M/s)\n' %(dataWritten, delta, (rate) / (1024*1024)  ))
+                    sys.stdout.flush()

                 # Calculate how much time we should give up to others
-                sleepTime = charityTime * ((dataWritten / delta) / (
(dataWritten / delta) * priorityPctDec))
-#                sys.stdout.write('DOING sleepTime is: %f\n' %(sleepTime,))
+                sleepTime = delta * (1.00 - priorityPctDec)
+                if DEBUG is True:
+                    sys.stdout.write('DOING sleepTime is: %f\n'
%(sleepTime,))
                 time.sleep(sleepTime)

                 # Adjust so that [ delta = (after - before) ] only
reflects time spent writing, and reset counter



I've only modified the direct algorithm (and uncommented some DEBUG) stuff.
This is all checked into new branch, "4.0branch".


Basically, we have a period defined by "delta". To simplify for now, I've
removed the concept of a "charityPeriod", which turns delta into a
simplified term, "time to write a single block/chunk", of the provided
block/chunk size.

So now, we measure our throughput on each block written, and adjust our
sleep time such that after the first block, we are maintaining a linear
average of the "priorityPct" percentage of bandwidth. This recalculates at
every block written, so that as total available bandwidth decreases or
increases, we maintain the same average percentage of available bandwidth.

I've ran through "testWrite.py" - and as expected (it's especially
noticable on my laptop which runs a RAID-1 of two SSDs) as priority goes
from 1 (highest) to 10, overall bandwidth decreases and sleepTime increases.

In this simplified algorithm, "charityRate" and "charityTime" are both
unused.

Please if you would like, overview this, and make any suggestions toward
improvements that you can think of.

I've thought of maybe keeping a rolling average of bandwidth, which would
"protect against spikes", but I think it better to do it block-at-a-time.
If you say "use 50% available bandwidth", you don't care if that bandwidth
changes, you care that 50% is still available for tasks that need it.

Maybe we could reintroduce the 'charityRate' to generate a 'charityPeriod'
-- basically instead of doing it block-at-a-time, we can do it something
like 5 blocks at a time, which finds a compromise between ensuring that we
are using "50% available bandwidth" even as bandwidth changes, yet we are
still better protected against spikes, which depending on how their timing
intersects with our timing, could make us THINK we are using 50% available
bandwidth, but if they are sleeping while we are sleeping and writing while
we are writing, we will actually be using less because our estimation will
be off.

So based on that rambling, I think I will do this:

1. Calculate the "total" bandwidth based on ~5 blocks (configurable).
2. Sleep every block 1/5th the time calculated, instead of 1 big sleep
every 5 blocks.

As I develop this now, I find that I'm coming closer and closer to the
original algorithm, and understanding why I came up with it (It's been a
long time and I've written much code since then, haha). I had a heuristic
approach to instead of using a static number of blocks, to have a
deterministic etc etc I'm sure you can see where I'm going. I just coded
that sleepTime param in error, but I think my original thinking was solid.

I look forward to your comments, and I will commit the above approach into
4.0branch for your evaluation.

**Comment by kata198** [comment] 2016-12-15 05:16
I've commited the following changes.While a single process is now
mathamatically fair in the context of itself, I need to do a fair amount of
testing to ensure that having multiple of these guys going are fair to
eachother, as that was the original goal. Please still feel to share any
ideas to improve the algorithm or other thoughts.:

diff --git a/nonblock/BackgroundWrite.py b/nonblock/BackgroundWrite.py
index 691055b..efb15ea 100644
--- a/nonblock/BackgroundWrite.py
+++ b/nonblock/BackgroundWrite.py
@@ -7,7 +7,7 @@
 '''
 # vim: ts=4 sw=4 expandtab

-#import sys
+import sys
 import threading
 import time

@@ -15,6 +15,10 @@ from collections import deque

 __all__ = ('BackgroundWriteProcess', 'BackgroundIOPriority', 'bgwrite',
'bgwrite_chunk', 'chunk_data')

+
+DEBUG = False
+
+
 def bgwrite(fileObj, data, closeWhenFinished=False, chainAfter=None,
ioPrio=4):
     '''
         bgwrite - Start a background writing process
@@ -65,9 +69,9 @@ class BackgroundIOPriority(object):
             See __init__ for fields
     '''

-    __slots__ = ('chainPollTime', 'defaultChunkSize', 'priorityPct',
'charityRate', 'charityTime')
+    __slots__ = ('chainPollTime', 'defaultChunkSize', 'bandwidthPct',
'numChunksRateSmoothing')

-    def __init__(self, chainPollTime, defaultChunkSize, priorityPct,
charityRate=1.85, charityTime=.0003):
+    def __init__(self, chainPollTime, defaultChunkSize, bandwidthPct,
numChunksRateSmoothing=5):
         '''
             __init__ - Create a BackgroundIOPriority.

@@ -81,34 +85,35 @@ class BackgroundIOPriority(object):
                 be used as the max size of each chunk. Each chunk is
written and a flush is issued (if the stream supports it).
                 Increasing this increases throughput while decreasing
interactivity

-            @param priorityPct - integer > 0, generally 0-100. When this
number is high, throughput for the operation will be higher. When it is
lower,
-               interactivity is higher, e.x. if you have a calculation
going and a write going, the lower this number the longer the write will
take, but the more
-               calculations will be performed during that period.
+            @param bandwidthPct - integer > 0 and < 100. This is the
percentage of overall bandwidth that this task will attempt to use.

-            @param charityRate - float >= 0, Every couple of blocks
written, the current throughput is checked and if things have been going
swiftly
-               a short sleep will be incurred. Increasing this number
causes that check to happen more often.
+              A high number means higher throughput at the cost of lest
interactivity for other tasks, a low number means the opposite.

-               This number is related to both the number of blocks and the
priorityPct. The default, should be fine, but you may find it better
-               as a different value in certain cases. Increasing or
decreasing could either increase or decrease interactivity, depending on
those other factors.
-               Generally, however, increasing this increases interactivity
and ability to write in parallel, at the cost of throughput.
+              So, for example, a bandwidthPct of "50" will attempt to use
"50%" of the available bandwidth. Note, this does not represent theroetical
+              max bandwidth, i.e. the max rate of the I/O device, but the
amount of available bandwidth available to this application. For example,
+              if this is given "100%", no throttling is performed. If this
is given "80%", then it calculates the average time to write a single chunk,
+              ( see #numChunksRateSmoothing for how many chunks are used
in evaluating this average ), and sleeps for then 20% of that time at the
end
+              of every chunk.

-            @param charityTime - float >= 0 - Used to calculate the time
to sleep when the charity period hits. The equation is:
-                sleepTime = charityTime * ((dataWritten / delta) / (
(dataWritten / delta) * priorityPctDec))
-                 Where dataWritten = number of bytes written already,
delta = total time spent writing (not including charity time sleeping)
-                 and priorityPctDec = priorityPct / 100.
-
-                 Increasing this can increase interactivity and allow more
parallel operations at the cost of throughput.
-                 The default should be fine for the majority of cases, but
it is tunable.
+            @param numChunksRateSmoothing - integer >= 1 , Default 5. This
is the number of chunks which are used in calculating the current
throughput rate.
+              See #bandwidthPct for the other half of the story. The
higher this number, the more "fair" your application will be against a
constant
+              rate of I/O by other applications, but the less able it may
be to play fair when the external I/O is spiking.

+              Also, consider that this is related to the
#defaultChunkSize, as it is not a constant period of time. The default of
"5" should be okay,
+              but you may want to tune it if you use really large or
really small chunk sizes.
+
+
             An "interactivity score" is defined to be (number of
calculations) / (time to write data).
         '''


         self.chainPollTime = chainPollTime
         self.defaultChunkSize = defaultChunkSize
-        self.priorityPct = float(priorityPct)
-        self.charityRate = float(charityRate)
-        self.charityTime = float(charityTime)
+        self.bandwidthPct = float(bandwidthPct)
+        if bandwidthPct <= 0 or bandwidthPct > 100:
+            raise ValueError('Given bandwidthPct %f must be > 0 and <=
100')
+
+        self.numChunksRateSmoothing = numChunksRateSmoothing

     def __getitem__(self, key):
         if key in BackgroundIOPriority.__slots__:
@@ -125,15 +130,15 @@ _SIZE_MEG = 1024 * 1024

 # BG_IO_PRIOS - Predefined I/O priorities, 1-10. The lower the number, the
more throughput at the cost of interactivity
 BG_IO_PRIOS = {
-    1  : BackgroundIOPriority(.0009, _SIZE_MEG * 5,    100), # Most
throughput, least interactivity, but still very interactive.
+    1  : BackgroundIOPriority(.0009, _SIZE_MEG * 5,    100), # Maximum
throughput, no regard for interactivity.
     2  : BackgroundIOPriority(.0009, _SIZE_MEG * 4,     90),
     3  : BackgroundIOPriority(.0015, _SIZE_MEG * 3,     80),
-    4  : BackgroundIOPriority(.0015, _SIZE_MEG * 2,     70),
+    4  : BackgroundIOPriority(.0015, _SIZE_MEG * 2,     75),
     5  : BackgroundIOPriority(.0019, _SIZE_MEG * 1.25,  65),
-    6  : BackgroundIOPriority(.0019, _SIZE_MEG * .6,   50),
-    7  : BackgroundIOPriority(.0024, _SIZE_MEG * .4,    40),
-    8  : BackgroundIOPriority(.0024, _SIZE_MEG * .25,   30),
-    9  : BackgroundIOPriority(.0031, _SIZE_MEG * .175,  30),
+    6  : BackgroundIOPriority(.0019, _SIZE_MEG * .6,   55),
+    7  : BackgroundIOPriority(.0024, _SIZE_MEG * .4,    45),
+    8  : BackgroundIOPriority(.0024, _SIZE_MEG * .25,   35),
+    9  : BackgroundIOPriority(.0031, _SIZE_MEG * .175,  31),
     10 : BackgroundIOPriority(.0100, _SIZE_MEG * .1,    25), # Least
throughput, most interactivity, very little throughput
 }

@@ -212,11 +217,9 @@ class BackgroundWriteProcess(threading.Thread):

         # Pull class data into locals
         fileObj = self.fileObj
-        priorityPct = self.backgroundIOPriority.priorityPct
-        priorityPctDec = priorityPct / 100.0
+        bandwidthPct = self.backgroundIOPriority.bandwidthPct
+        bandwidthPctDec = bandwidthPct / 100.0

-        charityRate = self.backgroundIOPriority.charityRate
-        charityTime = self.backgroundIOPriority.charityTime

         # Number of blocks, total
         numBlocks = len(self.remainingData)
@@ -234,16 +237,27 @@ class BackgroundWriteProcess(threading.Thread):
             doFlush = lambda obj : 1


-        # charityPeriod - How often we stop for a short bit to be gracious
to other running tasks
-        charityPeriod = int(max( (priorityPctDec * numBlocks) /
charityRate, 3 ))
+        # numChunksRateSmoothing - How often we stop for a short bit to be
gracious to other running tasks.
+        #  float for division below
+        numChunksRateSmoothing =
float(self.backgroundIOPriority.numChunksRateSmoothing)

-        # i will be the counter from 1 to charityPeriod, and then reset
+        # i will be the counter from 1 to numChunksRateSmoothing, and then
reset
         i = 1

+        # We start with using max bandwidth until we hit
#numChunksRateSmoothing , at which case we recalculate
+        #  sleepTime. We sleep after every block written to maintain a
desired average throughput based on
+        #  bandwidthPct
+        sleepTime = 0
+
         # Before represents the "start" time. When we sleep, we will
increment this value
         #  such that [ delta = (after - before) ] only accounts for time
we've spent writing,
         #  not in charity.
         before = time.time()
+
+        # timeSlept - Amount of time slept, which must be subtracted from
total time spend
+        #  to get an accurate picture of throughput.
+        timeSlept = 0
+
         while len(self.remainingData) > 0:

             # pop, write, flush
@@ -252,24 +266,35 @@ class BackgroundWriteProcess(threading.Thread):
             doFlush(fileObj)

             dataWritten += len(nextData)
-
-            if i == charityPeriod:
+            if sleepTime:
+                sleepBefore = time.time()
+
+                time.sleep(sleepTime)
+
+                sleepAfter = time.time()
+                timeSlept += (sleepAfter - sleepBefore)
+
+            if i == numChunksRateSmoothing:
                 # We've completed a full period, time for charity
                 after = time.time()

-                delta = after - before
-                # Uncomment the following to see rates
+                delta = after - before - timeSlept

-#                sys.stdout.write('\t  I have written %d bytes in %3.3f
seconds (%4.5f M/s)\n' %(dataWritten, delta, (dataWritten / delta) /
(1024*1024)  ))
-#                sys.stdout.flush()
+                rate = dataWritten / delta

-                # Calculate how much time we should give up to others
-                sleepTime = charityTime * ((dataWritten / delta) / (
(dataWritten / delta) * priorityPctDec))
-#                sys.stdout.write('DOING sleepTime is: %f\n' %(sleepTime,))
-                time.sleep(sleepTime)
+                if DEBUG is True:
+                    sys.stdout.write('\t  I have written %d bytes in %3.3f
seconds and slept %3.3f sec (%4.5f M/s over %3.3fs)\n' %(dataWritten,
delta, timeSlept, (rate) / (1024*1024), delta + timeSlept  ))
+                    sys.stdout.flush()
+
+                # Calculate how much time we should give up on each block
to other tasks
+                sleepTime = delta * (1.00 - bandwidthPctDec)
+                sleepTime /= numChunksRateSmoothing
+
+                if DEBUG is True:
+                    sys.stdout.write('Calculated new sleepTime to be:
%f\n' %(sleepTime,))

-                # Adjust so that [ delta = (after - before) ] only
reflects time spent writing, and reset counter
-                before += (time.time() - after)
+                timeSlept = 0
+                before = time.time()
                 i = 0

             i += 1

**Comment by kata198** [comment] 2017-01-04 22:12
So, no further input?

**Comment by kata198** [comment] 2017-01-06 22:29
Closing. Updates will be in 4.0 release.

**Closed as completed by kata198** 2017-01-06 22:29 UTC
